In [1]:
import os
import numpy as np
import pandas as pd

# 01. 수작업 데이터 정제

In [149]:
df = pd.read_excel(os.path.join('..', '0.Data', '01_제공데이터', 'meta_v01_0819.xlsx'))

In [150]:
df['상품코드'].nunique(), df['상품명'].nunique(), df['상품명다시'].nunique(),

(2042, 1687, 1083)

In [151]:
df.head()

,상품코드,상품명,상품군,판매단가,결제방법,상품명다시,단위,브랜드,옵션,종류,모델명,성별
0,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,0,남성 블랙 에디션 다이아몬드 워치,NaN,가이거,NaN,악세서리,NaN,NaN
1,200942,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,0,남성 블랙 에디션 다이아몬드 워치,NaN,가이거,NaN,악세서리,NaN,NaN
2,200948,무이자[가이거] 무빙스타 다이아몬드 워치,잡화,129000,2,무빙스타 다이아몬드 워치,NaN,가이거,NaN,악세서리,NaN,NaN
3,200951,일시불[가이거] 무빙스타 다이아몬드 워치,잡화,119000,1,무빙스타 다이아몬드 워치,NaN,가이거,NaN,악세서리,NaN,NaN
4,200946,[무이자] 가이거 무빙스타 다이아몬드 워치+보석함,잡화,119000,2,무빙스타 다이아몬드 워치 + 보석함,NaN,가이거,NaN,악세서리,NaN,NaN

In [152]:
df.loc[df['성별'].notnull(), '성별'].apply(lambda x : '남성' if x == 1 else ('여성' if x == 2 else None))

30      남성
31      여성
32      남성
33      여성
34      남성
        ..
1830    남성
1831    여성
1832    남성
1833    여성
1834    남성
Name: 성별, Length: 600, dtype: object

In [153]:
df.loc[df['성별'].notnull(), '상품명다시'] = df.loc[df['성별'].notnull(), '성별'].apply(lambda x : '남성' if x == 1 else ('여성' if x == 2 else '')) + ' ' + df.loc[df['성별'].notnull(), '상품명다시']

In [154]:
df['단위'] = df['단위'].astype(str)
df['브랜드'] = df['브랜드'].astype(str)
df['상품명다시'] = df['상품명다시'].astype(str)

In [157]:
df['NEW상품명'] = list(map(lambda x : ' '.join(x).replace('nan', '').strip(), df[['브랜드', '상품명다시', '단위']].values))

In [158]:
df.loc[df['상품군'] == '의류']

,상품코드,상품명,상품군,판매단가,결제방법,상품명다시,단위,브랜드,옵션,종류,모델명,성별,NEW상품명
30,201220,그렉노먼 남성 구스다운 롱 벤치코트,의류,119000,0,남성 구스다운 롱 벤치코트,nan,그렉노먼,NaN,2,NaN,1.0,그렉노먼 남성 구스다운 롱 벤치코트
31,201226,그렉노먼 여성 구스다운 롱 벤치코트,의류,119000,0,여성 구스다운 롱 벤치코트,nan,그렉노먼,NaN,2,NaN,2.0,그렉노먼 여성 구스다운 롱 벤치코트
32,201221,그렉노먼 남성 디보티 컬렉션 트렌치코트 1종,의류,49900,0,남성 디보티 컬렉션 트렌치코트,1종,그렉노먼,NaN,2,NaN,1.0,그렉노먼 남성 디보티 컬렉션 트렌치코트 1종
33,201227,그렉노먼 여성 디보티 컬렉션 트렌치코트 1종,의류,49900,0,여성 디보티 컬렉션 트렌치코트,1종,그렉노먼,NaN,2,NaN,2.0,그렉노먼 여성 디보티 컬렉션 트렌치코트 1종
34,201223,그렉노먼 남성 봄 컬렉션 티셔츠 5종,의류,59900,0,남성 봄 컬렉션 티셔츠,5종,그렉노먼,NaN,0,NaN,1.0,그렉노먼 남성 봄 컬렉션 티셔츠 5종
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1830,201215,USPA화이트라벨 남성트랙수트,의류,79000,0,남성 화이트라벨 트랙수트,nan,USPA,NaN,3,NaN,1.0,USPA 남성 화이트라벨 트랙수트
1831,201219,USPA화이트라벨 여성트랙수트,의류,79000,0,여성 화이트라벨 트랙수트,nan,USPA,NaN,3,NaN,2.0,USPA 여성 화이트라벨 트랙수트
1832,201198,19 SS USPA 남성 화이트라벨 폴로셔츠 3종,의류,79000,0,남성 화이트라벨 폴로셔츠,3종,USPA,2019 S/S,0,NaN,1.0,USPA 남성 화이트라벨 폴로셔츠 3종
1833,201199,19 SS USPA 여성 화이트라벨 폴로셔츠 3종,의류,79000,0,여성 화이트라벨 폴로셔츠,3종,USPA,2019 S/S,0,NaN,2.0,USPA 여성 화이트라벨 폴로셔츠 3종
1834,201214,USPA화이트라벨 남성모크넥세트,의류,79000,0,남성 모크넥세트,nan,USPA화이트라벨,NaN,4,NaN,1.0,USPA화이트라벨 남성 모크넥세트

In [159]:
df['NEW상품명'] = df['NEW상품명'].apply(lambda x : x.replace(',', '').replace('+', ' + ').replace('  ',' ').strip())

In [160]:
meta = df.copy()

In [161]:
meta.to_excel(os.path.join('..', '0.Data', '01_제공데이터', 'meta_v02_0819.xlsx'), index = False)

In [162]:
import gc
del df
gc.collect()

6325

# 02. 데이터 머징

In [163]:
df = pd.read_excel(os.path.join('..', '0.Data', '01_제공데이터', '2020 빅콘테스트 데이터분석분야-챔피언리그_2019년 실적데이터_v1_200818.xlsx'), skiprows = 1)

In [164]:
df.shape

(38309, 8)

In [165]:
df.head()

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0
1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0
3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000.0

In [166]:
df = df.merge(meta[['상품코드', 'NEW상품명', '결제방법', '단위', '브랜드', '옵션', '종류']], on = '상품코드', how = 'left')

In [167]:
# 예측 상품 중 판매가 0인 프로그램 실적은 예측에서 제외함(데이터 명세서)
df = df.loc[df['상품군'] != '무형']

In [168]:
# 2042개 상품 -> 1364개 상품으로 감소
df['상품코드'].nunique(), df['NEW상품명'].nunique()

(2042, 1364)

In [169]:
df['결제방법'] = df['결제방법'].astype(int)

In [171]:
df.loc[df['NEW상품명'].apply(lambda x : len(x.split()) < 2)]

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,NEW상품명,결제방법,단위,브랜드,옵션,종류
25626,2019-08-30 07:00:00,20.0,100056,200141,(일)모나코사놀,건강기능,139000,9233000.0,모나코사놀,1,nan,nan,NaN,건강식품
25627,2019-08-30 07:00:00,NaN,100056,200140,(무)모나코사놀,건강기능,149000,1817000.0,모나코사놀,2,nan,nan,NaN,건강식품
25628,2019-08-30 07:20:00,20.0,100056,200141,(일)모나코사놀,건강기능,139000,6606000.0,모나코사놀,1,nan,nan,NaN,건강식품
25629,2019-08-30 07:20:00,NaN,100056,200140,(무)모나코사놀,건강기능,149000,5251000.0,모나코사놀,2,nan,nan,NaN,건강식품
25630,2019-08-30 07:40:00,20.0,100056,200141,(일)모나코사놀,건강기능,139000,10905000.0,모나코사놀,1,nan,nan,NaN,건강식품
25631,2019-08-30 07:40:00,NaN,100056,200140,(무)모나코사놀,건강기능,149000,4714000.0,모나코사놀,2,nan,nan,NaN,건강식품
27621,2019-09-18 09:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,34533000.0,스팀큐다리미,0,nan,nan,NaN,NaN
27622,2019-09-18 09:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,32590000.0,스팀큐다리미,0,nan,nan,NaN,NaN
27623,2019-09-18 09:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,35692000.0,스팀큐다리미,0,nan,nan,NaN,NaN
27864,2019-09-20 12:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,12034000.0,스팀큐다리미,0,nan,nan,NaN,NaN
27865,2019-09-20 12:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,23104000.0,스팀큐다리미,0,nan,nan,NaN,NaN
27866,2019-09-20 12:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,33081000.0,스팀큐다리미,0,nan,nan,NaN,NaN
29369,2019-10-04 08:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,14772000.0,스팀큐다리미,0,nan,nan,NaN,NaN
29370,2019-10-04 08:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,26523000.0,스팀큐다리미,0,nan,nan,NaN,NaN
29371,2019-10-04 08:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,41066000.0,스팀큐다리미,0,nan,nan,NaN,NaN
30052,2019-10-10 09:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,20965000.0,스팀큐다리미,0,nan,nan,NaN,NaN
30053,2019-10-10 09:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,40854000.0,스팀큐다리미,0,nan,nan,NaN,NaN
30054,2019-10-10 09:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,47240000.0,스팀큐다리미,0,nan,nan,NaN,NaN
30657,2019-10-16 09:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,22300000.0,스팀큐다리미,0,nan,nan,NaN,NaN
30658,2019-10-16 09:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,37757000.0,스팀큐다리미,0,nan,nan,NaN,NaN
30659,2019-10-16 09:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,50860000.0,스팀큐다리미,0,nan,nan,NaN,NaN
30690,2019-10-16 18:00:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,6154000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
30691,2019-10-16 18:00:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,3257000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
30692,2019-10-16 18:20:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,11577000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
30693,2019-10-16 18:20:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,13589000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
30694,2019-10-16 18:40:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,24517000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
30695,2019-10-16 18:40:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,16161000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
31444,2019-10-23 20:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,23207000.0,스팀큐다리미,0,nan,nan,NaN,NaN
31445,2019-10-23 20:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,46588000.0,스팀큐다리미,0,nan,nan,NaN,NaN
31446,2019-10-23 20:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,52375000.0,스팀큐다리미,0,nan,nan,NaN,NaN
31596,2019-10-25 09:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,21237000.0,스팀큐다리미,0,nan,nan,NaN,NaN
31597,2019-10-25 09:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,40466000.0,스팀큐다리미,0,nan,nan,NaN,NaN
31598,2019-10-25 09:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,48543000.0,스팀큐다리미,0,nan,nan,NaN,NaN
31891,2019-10-28 19:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,22497000.0,스팀큐다리미,0,nan,nan,NaN,NaN
31892,2019-10-28 19:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,56109000.0,스팀큐다리미,0,nan,nan,NaN,NaN
31893,2019-10-28 19:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,66219000.0,스팀큐다리미,0,nan,nan,NaN,NaN
32042,2019-10-30 09:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,21159000.0,스팀큐다리미,0,nan,nan,NaN,NaN
32043,2019-10-30 09:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,37405000.0,스팀큐다리미,0,nan,nan,NaN,NaN
32044,2019-10-30 09:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,39548000.0,스팀큐다리미,0,nan,nan,NaN,NaN
32562,2019-11-04 14:20:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,8884000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
32563,2019-11-04 14:20:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,14773000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
32564,2019-11-04 14:40:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,16345000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
32565,2019-11-04 14:40:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,12238000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
32566,2019-11-04 15:00:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,19124000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
32567,2019-11-04 15:00:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,19966000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
34732,2019-11-26 19:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,25730000.0,스팀큐다리미,0,nan,nan,NaN,NaN
34733,2019-11-26 19:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,35281000.0,스팀큐다리미,0,nan,nan,NaN,NaN
34734,2019-11-26 19:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,44995000.0,스팀큐다리미,0,nan,nan,NaN,NaN
35388,2019-12-03 09:20:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,24260000.0,스팀큐다리미,0,nan,nan,NaN,NaN
35389,2019-12-03 09:40:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,32304000.0,스팀큐다리미,0,nan,nan,NaN,NaN
35390,2019-12-03 10:00:00,20.0,100052,200135,스팀큐다리미,생활용품,59800,32058000.0,스팀큐다리미,0,nan,nan,NaN,NaN
37739,2019-12-25 17:20:00,20.0,100843,202487,무이자 도깨비그릴,주방,159000,5266000.0,도깨비그릴,2,nan,nan,NaN,NaN
37740,2019-12-25 17:20:00,NaN,100843,202488,일시불 도깨비그릴,주방,149000,5475000.0,도깨비그릴,1,nan,nan,NaN,NaN
37741,2019-12-25 17:40:00,20.0,100843,202487,무이자 도깨비그릴,주방,159000,13389000.0,도깨비그릴,2,nan,nan,NaN,NaN
37742,2019-12-25 17:40:00,NaN,100843,202488,일시불 도깨비그릴,주방,149000,11457000.0,도깨비그릴,1,nan,nan,NaN,NaN
37743,2019-12-25 18:00:00,20.0,100843,202487,무이자 도깨비그릴,주방,159000,13316000.0,도깨비그릴,2,nan,nan,NaN,NaN
37744,2019-12-25 18:00:00,NaN,100843,202488,일시불 도깨비그릴,주방,149000,17885000.0,도깨비그릴,1,nan,nan,NaN,NaN

In [174]:
df.loc[df['NEW상품명'] == '쿠첸인버터전자레인지']

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,NEW상품명,결제방법,단위,브랜드,옵션,종류
30690,2019-10-16 18:00:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,6154000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
30691,2019-10-16 18:00:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,3257000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
30692,2019-10-16 18:20:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,11577000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
30693,2019-10-16 18:20:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,13589000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
30694,2019-10-16 18:40:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,24517000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
30695,2019-10-16 18:40:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,16161000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
32562,2019-11-04 14:20:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,8884000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
32563,2019-11-04 14:20:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,14773000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
32564,2019-11-04 14:40:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,16345000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
32565,2019-11-04 14:40:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,12238000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN
32566,2019-11-04 15:00:00,20.0,100449,201382,무이자 쿠첸인버터전자레인지 (COV-i230KGF),주방,189000,19124000.0,쿠첸인버터전자레인지,2,nan,nan,NaN,NaN
32567,2019-11-04 15:00:00,NaN,100449,201389,일시불 쿠첸인버터전자레인지 (COV-i230KGF),주방,179000,19966000.0,쿠첸인버터전자레인지,1,nan,nan,NaN,NaN

In [175]:
df.loc[df['NEW상품명'] == '쿠첸인버터전자레인지', '브랜드'] = '쿠첸'
df.loc[df['NEW상품명'] == '쿠첸인버터전자레인지', 'NEW상품명'] = '인버터 전자레인지'

In [178]:
meta.loc[meta['NEW상품명'] == '쿠첸인버터전자레인지', '브랜드'] = '쿠첸'
meta.loc[meta['NEW상품명'] == '쿠첸인버터전자레인지', 'NEW상품명'] = '인버터 전자레인지'

In [192]:
df.loc[df['단위'] == 'nan', '단위'] = None
meta.loc[meta['단위'] == 'nan', '단위'] = None
df.loc[df['브랜드'] == 'nan', '브랜드'] = None
meta.loc[meta['브랜드'] == 'nan', '브랜드'] = None

In [200]:
df.shape

(37372, 14)

In [193]:
meta.to_excel(os.path.join('..', '0.Data', '01_제공데이터', 'sale_meta_v02_0819.xlsx'), index = False)
df.to_excel(os.path.join('..', '0.Data', '01_제공데이터', 'sale_data_v02_0819.xlsx'), index = False)

In [206]:
temp = meta['NEW상품명'].drop_duplicates().reset_index()

In [212]:
temp['index'] = temp['index'].astype(str).str.zfill(6)

In [214]:
temp.to_excel(os.path.join('..', '0.Data', '01_제공데이터', 'item_meta_v01_0819.xlsx'), index = False)

# 03. 데이터 머징 업데이트(0820)

In [266]:
sale = pd.read_excel(os.path.join('..', '0.Data', '01_제공데이터', 'sale_data_v03_0820.xlsx'))
meta = pd.read_excel(os.path.join('..', '0.Data', '01_제공데이터', 'sale_meta_v03_0820.xlsx'))

## 03-01. 아이템코드 생성

In [249]:
item = meta['NEW상품명'].drop_duplicates().reset_index()
item['index'] = item.index.astype(str).str.zfill(6)

In [250]:
item.head()

    index                   NEW상품명
0  000000   가이거 남성 블랙 에디션 다이아몬드 워치
1  000001        가이거 무빙스타 다이아몬드 워치
2  000002  가이거 무빙스타 다이아몬드 워치 + 보석함
3  000003   가이거 여성 블랙 에디션 다이아몬드 워치
4  000004          가이거 제니스시계 주얼리세트

In [251]:
# 2042개의 상품코드 -> 1364개로 줄이기 성공!
item.shape

(1364, 2)

## 03-02. 새로운 상품명 및 코드 부여

In [258]:
meta = meta.merge(item, on = 'NEW상품명', how = 'left').rename(columns = {'index' : 'NEW상품코드'})

In [259]:
meta.head()

,상품코드,상품명,상품군,판매단가,결제방법,상품명다시,단위,브랜드,옵션,종류,모델명,성별,NEW상품명,NEW상품코드
0,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,0,남성 블랙 에디션 다이아몬드 워치,NaN,가이거,NaN,악세서리,NaN,NaN,가이거 남성 블랙 에디션 다이아몬드 워치,000000
1,200942,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,0,남성 블랙 에디션 다이아몬드 워치,NaN,가이거,NaN,악세서리,NaN,NaN,가이거 남성 블랙 에디션 다이아몬드 워치,000000
2,200948,무이자[가이거] 무빙스타 다이아몬드 워치,잡화,129000,2,무빙스타 다이아몬드 워치,NaN,가이거,NaN,악세서리,NaN,NaN,가이거 무빙스타 다이아몬드 워치,000001
3,200951,일시불[가이거] 무빙스타 다이아몬드 워치,잡화,119000,1,무빙스타 다이아몬드 워치,NaN,가이거,NaN,악세서리,NaN,NaN,가이거 무빙스타 다이아몬드 워치,000001
4,200946,[무이자] 가이거 무빙스타 다이아몬드 워치+보석함,잡화,119000,2,무빙스타 다이아몬드 워치 + 보석함,NaN,가이거,NaN,악세서리,NaN,NaN,가이거 무빙스타 다이아몬드 워치 + 보석함,000002

In [261]:
sale = sale.drop(['NEW상품코드', 'NEW상품명', '결제방법', '단위', '브랜드', '옵션' ,'종류'], axis = 1)

In [262]:
sale = sale.merge(meta[['상품코드', 'NEW상품코드', 'NEW상품명', '결제방법', '단위', '브랜드', '옵션', '종류']], on = '상품코드', how = 'left')

In [263]:
sale

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,NEW상품코드,NEW상품명,결제방법,단위,브랜드,옵션,종류
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0,000865,테이트 남성 셀린니트 3종,0,3종,테이트,NaN,0
1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0,000866,테이트 여성 셀린니트 3종,0,3종,테이트,NaN,0
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0,000865,테이트 남성 셀린니트 3종,0,3종,테이트,NaN,0
3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0,000866,테이트 여성 셀린니트 3종,0,3종,테이트,NaN,0
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000.0,000865,테이트 남성 셀린니트 3종,0,3종,테이트,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,2019-12-31 23:40:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000.0,000817,쿠첸 압력밥솥 6인용,1,6인용,쿠첸,NaN,NaN
37368,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000.0,000818,쿠첸 압력밥솥 10인용,2,10인용,쿠첸,NaN,NaN
37369,2020-01-01 00:00:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000.0,000818,쿠첸 압력밥솥 10인용,1,10인용,쿠첸,NaN,NaN
37370,2020-01-01 00:00:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000.0,000817,쿠첸 압력밥솥 6인용,2,6인용,쿠첸,NaN,NaN
37371,2020-01-01 00:00:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000.0,000817,쿠첸 압력밥솥 6인용,1,6인용,쿠첸,NaN,NaN

In [270]:
df = pd.read_excel(os.path.join('..', '0.Data', '01_제공데이터', '2020 빅콘테스트 데이터분석분야-챔피언리그_2019년 실적데이터_v1_200818.xlsx'), skiprows = 1)

In [276]:
df.shape

(38309, 8)

In [278]:
sale = pd.concat([sale, df.loc[df['상품군'] == '무형']], axis = 0).sort_values('방송일시')

In [282]:
meta.to_excel(os.path.join('..', '0.Data', '01_제공데이터', 'sale_meta_v03_0820.xlsx'), index = False)
sale.to_excel(os.path.join('..', '0.Data', '01_제공데이터', 'sale_data_v03_0820.xlsx'), index = False)
item.to_excel(os.path.join('..', '0.Data', '01_제공데이터', 'item_meta_v02_0820.xlsx'), index = False)